version: '3'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: ""
    networks:
      - kaliente-network
    environment:
      - POSTGRES_DB=kalientedb
      - POSTGRES_PASSWORD=8LQZjb0978U*
    volumes:
      - kaliente-db-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kalientepos-webapi:
    container_name: kalientepos-webapi
    image: kalientepos/webapi
    ports:
      - "8079:8079"
    networks:
      - kaliente-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/kalientedb
    depends_on:
      - postgresdb

networks:
  kaliente-network:

volumes:
  kaliente-db-vol:
