# Spring Boot configuration
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  # Multipart configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB
      location: ${java.io.tmpdir}
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kalientedb
    username: postgres
    password: 8LQZjb0978U*
  # JPA properties
  jpa:
    properties:
      hibernate:
        flush-mode: COMMIT
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8079 #set your port
# App configuration
app:
  mainCurrencyTitle: USD
# External assets dir configuration
  assets:
    absoluteRootPath: C:/Projects/KalientePOS/kaliente-pos-server/src/main/resources/static/public/
    productImages: product_images
    personnelProfileImages: personnel_profile_images